add USART requirements link for Semin
minel1410/maasu_internship_stm32 pull request #14
Opened 2024-11-28 11:06 UTC by seminmurtic

2024-11-28 11:24 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +   UE (Usart Enable) bit enable or disable the USART peripheral
enables or disables

2024-11-28 11:27 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable clock for GPIOA.
must enable clock for USART

2024-11-28 11:28 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable clock for USART1 on pins PA9(TX) and PA10 (RX)
koji registar se koristi za clock za USART1
napisati novi rq za clock za pinove

2024-11-28 11:28 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must set TX pin (PA9) as AF(Alternative Function)
koja af
pin mode

2024-11-28 11:29 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must set Baud Rate to 115200
baud rate nije fiksno 115200, tako da rq treba promijeniti da sistem mora biti u mogucnosti mijenjati baud rate kontrolom odredjenog registra

2024-11-28 11:29 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall set word lenght to 8bits
isto kao i za baud rate

2024-11-28 11:30 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   Set the number of stop bit to 1 stop bit
isto kao i za baud rate

2024-11-28 11:31 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable both transmission and reception modes for USART
moze biti samo transmission, samo receiver ili oboje

2024-11-28 11:33 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/non-functional_requirements.rst
> +   System should provide future with DMA for higher throughput.
rephrase, nema smisla rq

2024-11-28 12:11 UTC, minel1410 requested changes
@seminmurtic

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable clock for USART1_CR1
must enable clock for USART1 by setting the USART1_CR1 register

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall control Baud Rate by controlling specific register
navesti koji registart tacno

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall control word lenght by controlling specific register
isto kao i prethodni komentar

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall control the number of stop bit by controlling specific register.
koji registar

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable transmission mode for USART
sistem mora biti u mogucnosti da odabere transmiter, receiver ili oba moda u zavisnosti od parametra

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +   USART provides parity control even for error detection.
rephrase

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
navesti koje AF koriste USART1, 2, 6

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +   USART provides even parity control for error detection
ponavlja se

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +
navesti u cemu se razlikuju error detection

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +   With 16x oversampling the signal is more stable
rephrase npr. 16x oversampling provides more stable signal

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/informational_requirements.rst
> +   With 8x oversampling allows for faster data transmission, but with potential loss in accuracy.
isto kao i za 16x oversampling

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/non-functional_requirements.rst
> +   System should maintain stable communication at high baud rates without data loss
sta znaci stable, definisati

2024-11-28 12:11 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/non-functional_requirements.rst
> +   Each USART function must use no more than 13KB of available memory to minimize the impact on system resources.
minimize je weak word

2024-11-28 13:25 UTC, minel1410 requested changes
looks good, minor fixes left

2024-11-28 13:25 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must enable clock for USART1_CR1 by setting the USART1_CR1 register
must enable clock for USART1

2024-11-28 13:25 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall disable USART before configuration.
ovaj mozes obrisati posto ponavljas dole ispod

2024-11-28 13:25 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System must set the USART_CR1_UE value to 0.
ovdje samo dodati before configuration

2024-11-28 13:25 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
> +   System shall control word lenght by controlling USART_CR1
length*

2024-11-28 23:38 UTC, seminmurtic commented on docs/source/userdoc/requirements/interns/semin-murtic/USART/functional_requirements.rst
naveo u informational reqs

2024-11-29 08:27 UTC, minel1410 requested changes
rq su ok, samo je potrebno dodati USART_requirements link u toctree u glavni requirements.rst

2024-11-29 08:56 UTC, minel1410 approved these changes
Looks good :)

2024-11-29 08:56 UTC, merged