add USART requirements Lamija Fatic
minel1410/maasu_internship_stm32 pull request #18
Opened 2024-12-02 12:58 UTC by lamijafatic

2024-12-03 08:09 UTC, minel1410 requested changes
super je sve, samo par greskica na nefunkcionalnim
@lamijafatic

2024-12-03 08:09 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must ensure reliable USART communication with minimal data loss.
reliable, minimal su weak words

2024-12-03 08:09 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must provide a user-friendly interface for configuration and management of USART communication parameters, including baud rate and pin mappings.
funkcionalni rq

2024-12-03 08:09 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must support easy maintenance, with well-documented configuration parameters and clear error logs for debugging USART communication.
funkcionalni rq

2024-12-03 08:09 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must be portable to different microcontroller models that support USART communication with minimal configuration.
minimal weak word

2024-12-03 08:09 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must meet the timing constraints for USART data transmission and reception, ensuring that each operation completes within specified time windows.
potrebno je posebno navesti vrijeme za koje se operacije izvrsavaju

2024-12-04 09:08 UTC, minel1410 requested changes
jos jedna mala greskica 
@lamijafatic

2024-12-04 09:08 UTC, minel1410 commented on docs/source/userdoc/requirements/interns/lamija-fatic/USART_requirements/non-functional_requirements.rst
> +   The system must ensure reliable USART communication with reliable data loss.
idalje ovo nije uredu, prvo sto nema smisla reliable data loss, potrebna nam je tacna mjera koliki moze biti data loss; npr maksimalan gubitaka podataka ne smije prelaziti 0.1% ukupne kolicine podataka

2024-12-04 09:30 UTC, lamijafatic commented
Done

2024-12-04 12:20 UTC, minel1410 approved these changes
done :)

2024-12-04 12:21 UTC, minel1410 approved these changes

2024-12-04 12:21 UTC, merged